name: theory

dependencies:
  - python=3.9
  - pip>=19.0
  - pytest
  - jupyter
  - apple::tensorflow-deps
  - flask==1.1.2
  - python-dotenv==0.19.0
  - yaspin==1.4.1
  - boto3==1.17.29
  - botocore==1.20.29
  - tqdm==4.59.0
  - progressbar==2.5
  - wandb==0.11.2
  - python-benedict==0.24.0
  - pip:
      - tensorflow-macos
      - tensorflow-metal
      - tensorflow_datasets
